In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

def gauss_elimination(a, y):
    n = len(y)
    
    # Elimination phase
    for i in range(n-1):
        for j in range(i+1, n):
            factor = a[j, i] / a[i, i]
            a[j, i:] -= factor * a[i, i:]
            y[j] -= factor * y[i]
    
    # Back substitution
    x = np.zeros(n)
    x[-1] = y[-1] / a[-1, -1]
    for i in range(n-2, -1, -1):
        x[i] = (y[i] - np.dot(a[i, i+1:], x[i+1:])) / a[i, i]

    # Combine a and y into an augmented matrix
    augmented_matrix = np.concatenate((a, y[:, np.newaxis]), axis=1)

    return x, augmented_matrix

# Sample 1
a1 = np.array([[1, 2, 3], [3, 4, 5], [3, 5, 5]], dtype=float)
y1 = np.array([2, 2, 5], dtype=float)
upper_triangular_matrix_1 = np.copy(a1)
x1, augmented_matrix_1 = gauss_elimination(a1, y1)
print("Sample 1")
print("upper triangular matrix:")
print(upper_triangular_matrix_1)
print("Augmented matrix:")
print(augmented_matrix_1)
print("x:")
print(x1)

# Sample 2
a2 = np.array([[1, 2, 3, 4], [5, 4, 3, 2], [2, 1, 2, 4], [2, 1, 3, 4]], dtype=float)
y2 = np.array([4, 8, 5, 6], dtype=float)
upper_triangular_matrix_2 = np.copy(a2)
x2, augmented_matrix_2 = gauss_elimination(a2, y2)
print("\nSample 2")
print("upper triangular matrix:")
print(upper_triangular_matrix_2)
print("Augmented matrix:")
print(augmented_matrix_2)
print("x:")
print(x2)


Sample 1
upper triangular matrix:
[[1. 2. 3.]
 [3. 4. 5.]
 [3. 5. 5.]]
Augmented matrix:
[[ 1.  2.  3.  2.]
 [ 0. -2. -4. -4.]
 [ 0.  0. -2.  1.]]
x:
[-2.5  3.  -0.5]

Sample 2
upper triangular matrix:
[[1. 2. 3. 4.]
 [5. 4. 3. 2.]
 [2. 1. 2. 4.]
 [2. 1. 3. 4.]]
Augmented matrix:
[[  1.    2.    3.    4.    4. ]
 [  0.   -6.  -12.  -18.  -12. ]
 [  0.    0.    2.    5.    3. ]
 [  0.    0.    0.   -2.5  -0.5]]
x:
[ 1.4 -0.6  1.   0.2]
